//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_20._101_Farukov_UP___Cable_TV_Service_Company.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.ServicePackage = new HashSet<ServicePackage>();
        }
    
        public int RequestID { get; set; }
        public int IDClient { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<System.DateTime> RequestApprovalDate { get; set; }
        public int IDRequestStatus { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePackage> ServicePackage { get; set; }
    }
}
